=== e-dimensionz/Todoyu-PHP7.x/core/config/rights.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified"
		   elementFormDefault="qualified"
		   targetNamespace="http://www.todoyu.com/schema/rights"
		   xmlns="http://www.todoyu.com/schema/rights"
		   xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="rights" type="rightsType"/>
	<xs:complexType name="rightsType">
		<xs:sequence>
			<xs:element type="sectionType" name="section" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="sectionType">
		<xs:sequence>
			<xs:element type="rightType" name="right" maxOccurs="unbounded" minOccurs="1"/>
		</xs:sequence>
		<xs:attribute type="xs:string" name="name" use="required"/>
		<xs:attribute type="xs:string" name="require" use="optional"/>
	</xs:complexType>
	<xs:complexType name="rightType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="name" use="required"/>
				<xs:attribute type="xs:string" name="require" use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:schema>

=== e-dimensionz/Todoyu-PHP7.x/ext/calendar/config/rights.xml
<?xml version="1.0" encoding="utf-8"?>
<rights	xmlns="http://www.todoyu.com/schema/rights"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://www.todoyu.com/schema/rights ../../../core/config/rights.xsd">

	<section name="general">
		<right name="use" />
		<right name="area" require="general:use" />
	</section>

	<section name="event" require="general:area">
		<right name="seeAll" />
		<right name="add" />
		<right name="editAssigned" />
		<right name="deleteAssigned" />
		<right name="editAll" require="event:seeAll,event:editAssigned" />
		<right name="deleteAll" require="event:seeAll,event:editAssigned" />
		<right name="editInPast" require="event:editAssigned" />
		<right name="deleteInPast" require="event:deleteAssigned" />
	</section>

	<section name="mailing" require="event:add">
		<right name="sendAsEmail" />
	</section>

	<section name="reminders" require="general:use">
		<right name="popup" />
		<right name="email" />
	</section>

</rights>
